// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductionApi.Data;

#nullable disable

namespace ProductionApi.Migrations
{
    [DbContext(typeof(ProductionDbContext))]
    [Migration("20260428175225_UpdateDetailsTable")]
    partial class UpdateDetailsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductionApi.Models.Detail", b =>
                {
                    b.Property<int>("DetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailID"));

                    b.Property<decimal?>("ConsumptionRate")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("DetailCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DetailName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("DetailShortCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MainMaterial")
                        .HasColumnType("int");

                    b.HasKey("DetailID");

                    b.HasIndex("MainMaterial");

                    b.ToTable("Details");
                });

            modelBuilder.Entity("ProductionApi.Models.DetailToDetailReconfigurationTime", b =>
                {
                    b.Property<int>("ReconfigurationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReconfigurationID"));

                    b.Property<int>("EquipmentID")
                        .HasColumnType("int");

                    b.Property<int>("FromDetailID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("ReconfigurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("ToDetailID")
                        .HasColumnType("int");

                    b.HasKey("ReconfigurationID");

                    b.HasIndex("EquipmentID");

                    b.HasIndex("FromDetailID");

                    b.HasIndex("ToDetailID");

                    b.ToTable("DetailToDetailReconfigurationTimes");
                });

            modelBuilder.Entity("ProductionApi.Models.Equipment", b =>
                {
                    b.Property<int>("EquipmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentID"));

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EquipmentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("WorkPlaceID")
                        .HasColumnType("int");

                    b.HasKey("EquipmentID");

                    b.HasIndex("WorkPlaceID");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("ProductionApi.Models.EquipmentTimeSheet", b =>
                {
                    b.Property<int>("EquipmentTimeSheetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentTimeSheetID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DayType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("EquipmentID")
                        .HasColumnType("int");

                    b.Property<decimal?>("HoursWorked")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShiftCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EquipmentTimeSheetID");

                    b.HasIndex("EquipmentID");

                    b.ToTable("EquipmentTimeSheet");
                });

            modelBuilder.Entity("ProductionApi.Models.Material", b =>
                {
                    b.Property<int>("MaterialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialID"));

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MaterialID");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("ProductionApi.Models.MaterialMaterialSize", b =>
                {
                    b.Property<int>("MaterialID")
                        .HasColumnType("int");

                    b.Property<int>("MaterialSizeID")
                        .HasColumnType("int");

                    b.HasKey("MaterialID", "MaterialSizeID");

                    b.HasIndex("MaterialSizeID");

                    b.ToTable("MaterialMaterialSizes");
                });

            modelBuilder.Entity("ProductionApi.Models.MaterialSize", b =>
                {
                    b.Property<int>("MaterialSizeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialSizeID"));

                    b.Property<decimal>("SizeValue")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaterialSizeID");

                    b.ToTable("MaterialSizes");
                });

            modelBuilder.Entity("ProductionApi.Models.MaterialStock", b =>
                {
                    b.Property<int>("MaterialStockID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialStockID"));

                    b.Property<decimal>("CurrentQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaterialID")
                        .HasColumnType("int");

                    b.Property<int>("MaterialSizeID")
                        .HasColumnType("int");

                    b.Property<decimal>("ReceivedQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UsedQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaterialStockID");

                    b.HasIndex("MaterialSizeID");

                    b.HasIndex("MaterialID", "MaterialSizeID")
                        .IsUnique();

                    b.ToTable("MaterialStocks");
                });

            modelBuilder.Entity("ProductionApi.Models.MaterialTransaction", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionID"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("DocumentNumber")
                        .HasColumnType("int");

                    b.Property<int>("MaterialID")
                        .HasColumnType("int");

                    b.Property<int>("MaterialSizeID")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TransactionID");

                    b.HasIndex("MaterialID");

                    b.HasIndex("MaterialSizeID");

                    b.ToTable("MaterialTransactions");
                });

            modelBuilder.Entity("ProductionApi.Models.Operation", b =>
                {
                    b.Property<int>("OperationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OperationID"));

                    b.Property<int>("CompletedQuantity")
                        .HasColumnType("int");

                    b.Property<int>("DetailID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("EquipmentID")
                        .HasColumnType("int");

                    b.Property<int>("PlannedQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("OperationID");

                    b.HasIndex("DetailID");

                    b.HasIndex("EquipmentID");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("ProductionApi.Models.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonID"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PersonID");

                    b.ToTable("People");
                });

            modelBuilder.Entity("ProductionApi.Models.ShiftWorkLog", b =>
                {
                    b.Property<int>("ShiftWorkLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftWorkLogID"));

                    b.Property<int>("MasterID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("PersonID")
                        .HasColumnType("int");

                    b.Property<int>("ShiftNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ShiftWorkLogID");

                    b.HasIndex("MasterID");

                    b.HasIndex("PersonID");

                    b.ToTable("ShiftWorkLogs");
                });

            modelBuilder.Entity("ProductionApi.Models.ShiftWorkLogEquipment", b =>
                {
                    b.Property<int>("ShiftWorkLogID")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentID")
                        .HasColumnType("int");

                    b.HasKey("ShiftWorkLogID", "EquipmentID");

                    b.HasIndex("EquipmentID");

                    b.ToTable("ShiftWorkLogEquipments");
                });

            modelBuilder.Entity("ProductionApi.Models.ShiftWorkLogSetupPerson", b =>
                {
                    b.Property<int>("ShiftWorkLogID")
                        .HasColumnType("int");

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.HasKey("ShiftWorkLogID", "PersonID");

                    b.HasIndex("PersonID");

                    b.ToTable("ShiftWorkLogSetupPeople");
                });

            modelBuilder.Entity("ProductionApi.Models.TimeSheet", b =>
                {
                    b.Property<int>("TimeSheetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimeSheetID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DayType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("HoursWorked")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.Property<string>("ShiftCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TimeSheetID");

                    b.HasIndex("PersonID");

                    b.ToTable("TimeSheet");
                });

            modelBuilder.Entity("ProductionApi.Models.WorkPlace", b =>
                {
                    b.Property<int>("WorkPlaceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkPlaceID"));

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("WorkPlaceID");

                    b.ToTable("WorkPlaces");
                });

            modelBuilder.Entity("ProductionApi.Models.Detail", b =>
                {
                    b.HasOne("ProductionApi.Models.Material", "Material")
                        .WithMany("Details")
                        .HasForeignKey("MainMaterial")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Material");
                });

            modelBuilder.Entity("ProductionApi.Models.DetailToDetailReconfigurationTime", b =>
                {
                    b.HasOne("ProductionApi.Models.Equipment", "Equipment")
                        .WithMany("ReconfigurationTimes")
                        .HasForeignKey("EquipmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductionApi.Models.Detail", "FromDetail")
                        .WithMany("FromReconfigurations")
                        .HasForeignKey("FromDetailID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductionApi.Models.Detail", "ToDetail")
                        .WithMany("ToReconfigurations")
                        .HasForeignKey("ToDetailID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("FromDetail");

                    b.Navigation("ToDetail");
                });

            modelBuilder.Entity("ProductionApi.Models.Equipment", b =>
                {
                    b.HasOne("ProductionApi.Models.WorkPlace", "WorkPlace")
                        .WithMany("Equipments")
                        .HasForeignKey("WorkPlaceID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("WorkPlace");
                });

            modelBuilder.Entity("ProductionApi.Models.EquipmentTimeSheet", b =>
                {
                    b.HasOne("ProductionApi.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("ProductionApi.Models.MaterialMaterialSize", b =>
                {
                    b.HasOne("ProductionApi.Models.Material", "Material")
                        .WithMany("MaterialMaterialSizes")
                        .HasForeignKey("MaterialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductionApi.Models.MaterialSize", "MaterialSize")
                        .WithMany("MaterialMaterialSizes")
                        .HasForeignKey("MaterialSizeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("MaterialSize");
                });

            modelBuilder.Entity("ProductionApi.Models.MaterialStock", b =>
                {
                    b.HasOne("ProductionApi.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductionApi.Models.MaterialSize", "MaterialSize")
                        .WithMany()
                        .HasForeignKey("MaterialSizeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("MaterialSize");
                });

            modelBuilder.Entity("ProductionApi.Models.MaterialTransaction", b =>
                {
                    b.HasOne("ProductionApi.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductionApi.Models.MaterialSize", "MaterialSize")
                        .WithMany()
                        .HasForeignKey("MaterialSizeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("MaterialSize");
                });

            modelBuilder.Entity("ProductionApi.Models.Operation", b =>
                {
                    b.HasOne("ProductionApi.Models.Detail", "Detail")
                        .WithMany("Operations")
                        .HasForeignKey("DetailID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductionApi.Models.Equipment", "Equipment")
                        .WithMany("Operations")
                        .HasForeignKey("EquipmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Detail");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("ProductionApi.Models.ShiftWorkLog", b =>
                {
                    b.HasOne("ProductionApi.Models.Person", "Master")
                        .WithMany()
                        .HasForeignKey("MasterID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductionApi.Models.Person", null)
                        .WithMany("MasterShiftLogs")
                        .HasForeignKey("PersonID");

                    b.Navigation("Master");
                });

            modelBuilder.Entity("ProductionApi.Models.ShiftWorkLogEquipment", b =>
                {
                    b.HasOne("ProductionApi.Models.Equipment", "Equipment")
                        .WithMany("ShiftWorkLogs")
                        .HasForeignKey("EquipmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductionApi.Models.ShiftWorkLog", "ShiftWorkLog")
                        .WithMany("Equipments")
                        .HasForeignKey("ShiftWorkLogID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("ShiftWorkLog");
                });

            modelBuilder.Entity("ProductionApi.Models.ShiftWorkLogSetupPerson", b =>
                {
                    b.HasOne("ProductionApi.Models.Person", "Person")
                        .WithMany("ShiftWorkLogSetupPeople")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductionApi.Models.ShiftWorkLog", "ShiftWorkLog")
                        .WithMany("SetupPeople")
                        .HasForeignKey("ShiftWorkLogID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("ShiftWorkLog");
                });

            modelBuilder.Entity("ProductionApi.Models.TimeSheet", b =>
                {
                    b.HasOne("ProductionApi.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("ProductionApi.Models.Detail", b =>
                {
                    b.Navigation("FromReconfigurations");

                    b.Navigation("Operations");

                    b.Navigation("ToReconfigurations");
                });

            modelBuilder.Entity("ProductionApi.Models.Equipment", b =>
                {
                    b.Navigation("Operations");

                    b.Navigation("ReconfigurationTimes");

                    b.Navigation("ShiftWorkLogs");
                });

            modelBuilder.Entity("ProductionApi.Models.Material", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("MaterialMaterialSizes");
                });

            modelBuilder.Entity("ProductionApi.Models.MaterialSize", b =>
                {
                    b.Navigation("MaterialMaterialSizes");
                });

            modelBuilder.Entity("ProductionApi.Models.Person", b =>
                {
                    b.Navigation("MasterShiftLogs");

                    b.Navigation("ShiftWorkLogSetupPeople");
                });

            modelBuilder.Entity("ProductionApi.Models.ShiftWorkLog", b =>
                {
                    b.Navigation("Equipments");

                    b.Navigation("SetupPeople");
                });

            modelBuilder.Entity("ProductionApi.Models.WorkPlace", b =>
                {
                    b.Navigation("Equipments");
                });
#pragma warning restore 612, 618
        }
    }
}
